apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-shared
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://victoriametrics:8428
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'ZCloud'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
data:
  node-exporter.json: |
    {
      "annotations": { "list": [] },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 1,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineWidth": 2, "pointSize": 5, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" } },
              "mappings": [],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }, { "color": "red", "value": 80 }] },
              "unit": "percent"
            }
          },
          "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
          "id": 1,
          "options": { "legend": { "calcs": ["mean", "max"], "displayMode": "table", "placement": "bottom" }, "tooltip": { "mode": "multi" } },
          "targets": [{ "expr": "100 - (avg by(node) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)", "legendFormat": "{{ node }}", "refId": "A" }],
          "title": "CPU Usage por Nodo",
          "type": "timeseries"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineWidth": 2, "pointSize": 5, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" } },
              "mappings": [],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }, { "color": "red", "value": 80 }] },
              "unit": "percent"
            }
          },
          "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
          "id": 2,
          "options": { "legend": { "calcs": ["mean", "max"], "displayMode": "table", "placement": "bottom" }, "tooltip": { "mode": "multi" } },
          "targets": [{ "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100", "legendFormat": "{{ node }}", "refId": "A" }],
          "title": "Memory Usage por Nodo",
          "type": "timeseries"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [],
              "max": 100,
              "min": 0,
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }, { "color": "yellow", "value": 70 }, { "color": "red", "value": 85 }] },
              "unit": "percent"
            }
          },
          "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
          "id": 3,
          "options": { "orientation": "auto", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false }, "showThresholdLabels": false, "showThresholdMarkers": true },
          "targets": [{ "expr": "(1 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})) * 100", "legendFormat": "{{ node }}", "refId": "A" }],
          "title": "Disk Usage / (root)",
          "type": "gauge"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineWidth": 2, "pointSize": 5, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" } },
              "mappings": [],
              "unit": "Bps"
            }
          },
          "gridPos": { "h": 6, "w": 9, "x": 6, "y": 8 },
          "id": 4,
          "options": { "legend": { "calcs": ["mean"], "displayMode": "table", "placement": "bottom" }, "tooltip": { "mode": "multi" } },
          "targets": [
            { "expr": "irate(node_network_receive_bytes_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*\"}[5m])", "legendFormat": "{{ node }} rx {{ device }}", "refId": "A" },
            { "expr": "-irate(node_network_transmit_bytes_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*\"}[5m])", "legendFormat": "{{ node }} tx {{ device }}", "refId": "B" }
          ],
          "title": "Network I/O",
          "type": "timeseries"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineWidth": 2, "pointSize": 5, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" } },
              "mappings": [],
              "unit": "Bps"
            }
          },
          "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
          "id": 5,
          "options": { "legend": { "calcs": ["mean"], "displayMode": "table", "placement": "bottom" }, "tooltip": { "mode": "multi" } },
          "targets": [
            { "expr": "irate(node_disk_read_bytes_total[5m])", "legendFormat": "{{ node }} read {{ device }}", "refId": "A" },
            { "expr": "-irate(node_disk_written_bytes_total[5m])", "legendFormat": "{{ node }} write {{ device }}", "refId": "B" }
          ],
          "title": "Disk I/O",
          "type": "timeseries"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [{ "options": { "0": { "color": "red", "text": "DOWN" }, "1": { "color": "green", "text": "UP" } }, "type": "value" }],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "red", "value": null }, { "color": "green", "value": 1 }] }
            }
          },
          "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
          "id": 6,
          "options": { "colorMode": "background", "graphMode": "none", "justifyMode": "center", "orientation": "horizontal", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false }, "textMode": "auto" },
          "targets": [{ "expr": "up{job=\"node-exporter\"}", "legendFormat": "{{ node }}", "refId": "A" }],
          "title": "Node Status",
          "type": "stat"
        }
      ],
      "refresh": "30s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": ["zcloud", "nodes"],
      "templating": {
        "list": [
          {
            "current": { "selected": false, "text": "VictoriaMetrics", "value": "VictoriaMetrics" },
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "name": "datasource",
            "options": [],
            "query": "prometheus",
            "queryValue": "",
            "refresh": 1,
            "regex": "",
            "type": "datasource"
          }
        ]
      },
      "time": { "from": "now-1h", "to": "now" },
      "timepicker": {},
      "timezone": "browser",
      "title": "ZCloud - Node Overview",
      "uid": "zcloud-nodes",
      "version": 1
    }
  kubernetes-cluster.json: |
    {
      "annotations": { "list": [] },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 1,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }] }
            }
          },
          "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
          "id": 1,
          "options": { "colorMode": "value", "graphMode": "none", "justifyMode": "center", "orientation": "auto", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false }, "textMode": "auto" },
          "targets": [{ "expr": "count(kube_node_info)", "refId": "A" }],
          "title": "Nodes",
          "type": "stat"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }] }
            }
          },
          "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
          "id": 2,
          "options": { "colorMode": "value", "graphMode": "none", "justifyMode": "center", "orientation": "auto", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false }, "textMode": "auto" },
          "targets": [{ "expr": "count(kube_pod_info)", "refId": "A" }],
          "title": "Pods",
          "type": "stat"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }, { "color": "red", "value": 1 }] }
            }
          },
          "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
          "id": 3,
          "options": { "colorMode": "value", "graphMode": "none", "justifyMode": "center", "orientation": "auto", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false }, "textMode": "auto" },
          "targets": [{ "expr": "count(kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\"})", "refId": "A" }],
          "title": "Pods Not Running",
          "type": "stat"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineWidth": 2, "pointSize": 5, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" } },
              "mappings": [],
              "unit": "percent"
            }
          },
          "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
          "id": 4,
          "options": { "legend": { "calcs": ["mean", "max"], "displayMode": "table", "placement": "bottom" }, "tooltip": { "mode": "multi" } },
          "targets": [{ "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[5m])) by (namespace) * 100", "legendFormat": "{{ namespace }}", "refId": "A" }],
          "title": "CPU por Namespace",
          "type": "timeseries"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineWidth": 2, "pointSize": 5, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" } },
              "mappings": [],
              "unit": "bytes"
            }
          },
          "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
          "id": 5,
          "options": { "legend": { "calcs": ["mean", "max"], "displayMode": "table", "placement": "bottom" }, "tooltip": { "mode": "multi" } },
          "targets": [{ "expr": "sum(container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}) by (namespace)", "legendFormat": "{{ namespace }}", "refId": "A" }],
          "title": "Memory por Namespace",
          "type": "timeseries"
        },
        {
          "datasource": { "type": "prometheus", "uid": "${datasource}" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineWidth": 2, "pointSize": 5, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" } },
              "mappings": [],
              "unit": "Bps"
            }
          },
          "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
          "id": 6,
          "options": { "legend": { "calcs": ["mean"], "displayMode": "table", "placement": "bottom" }, "tooltip": { "mode": "multi" } },
          "targets": [
            { "expr": "sum(rate(container_network_receive_bytes_total[5m])) by (namespace)", "legendFormat": "{{ namespace }} rx", "refId": "A" },
            { "expr": "-sum(rate(container_network_transmit_bytes_total[5m])) by (namespace)", "legendFormat": "{{ namespace }} tx", "refId": "B" }
          ],
          "title": "Network I/O por Namespace",
          "type": "timeseries"
        }
      ],
      "refresh": "30s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": ["zcloud", "kubernetes"],
      "templating": {
        "list": [
          {
            "current": { "selected": false, "text": "VictoriaMetrics", "value": "VictoriaMetrics" },
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "name": "datasource",
            "options": [],
            "query": "prometheus",
            "refresh": 1,
            "type": "datasource"
          }
        ]
      },
      "time": { "from": "now-1h", "to": "now" },
      "timepicker": {},
      "timezone": "browser",
      "title": "ZCloud - Kubernetes Cluster",
      "uid": "zcloud-k8s",
      "version": 1
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
      containers:
        - name: grafana
          image: grafana/grafana:10.3.1
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "zcloud-admin-2026"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_SERVER_ROOT_URL
              value: "https://grafana.zyrak.cloud"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-clock-panel,grafana-piechart-panel"
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-providers
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-data
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-providers
          configMap:
            name: grafana-dashboard-providers
        - name: dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000