---
# Wazuh Manager Service
apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  type: ClusterIP
  ports:
    - name: agent-events
      port: 1514
      targetPort: 1514
      protocol: TCP
    - name: agent-enrollment
      port: 1515
      targetPort: 1515
      protocol: TCP
    - name: api
      port: 55000
      targetPort: 55000
      protocol: TCP
    - name: syslog
      port: 514
      targetPort: 514
      protocol: UDP
    - name: syslog-tcp
      port: 1514
      targetPort: 1514
      protocol: UDP
  selector:
    app: wazuh-manager
---
# NodePort service for agent communication from outside cluster
# Agents will connect to this port on any node
apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager-agents
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  type: NodePort
  ports:
    - name: agent-events
      port: 1514
      targetPort: 1514
      nodePort: 31514
      protocol: TCP
    - name: agent-enrollment
      port: 1515
      targetPort: 1515
      nodePort: 31515
      protocol: TCP
  selector:
    app: wazuh-manager
---
# Wazuh Manager ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-manager-config
  namespace: wazuh
data:
  ossec.conf: |
    <ossec_config>
      <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
        <logall_json>no</logall_json>
        <email_notification>no</email_notification>
        <smtp_server>localhost</smtp_server>
        <email_from>wazuh@zcloud</email_from>
        <email_to>admin@zcloud</email_to>
        <email_maxperhour>12</email_maxperhour>
        <email_log_source>alerts.log</email_log_source>
      </global>
      
      <alerts>
        <log_alert_level>3</log_alert_level>
        <email_alert_level>12</email_alert_level>
      </alerts>
      
      <!-- Agent connection settings -->
      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
        <queue_size>131072</queue_size>
      </remote>
      
      <!-- Agent enrollment (authd) -->
      <auth>
        <disabled>no</disabled>
        <port>1515</port>
        <use_source_ip>no</use_source_ip>
        <purge>yes</purge>
        <use_password>yes</use_password>
        <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
        <ssl_verify_host>no</ssl_verify_host>
        <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
        <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
        <ssl_auto_negotiate>no</ssl_auto_negotiate>
      </auth>
      
      <!-- Cluster disabled (single manager) -->
      <cluster>
        <name>wazuh</name>
        <node_name>manager</node_name>
        <node_type>master</node_type>
        <key>zcloud-wazuh-cluster-key</key>
        <port>1516</port>
        <bind_addr>0.0.0.0</bind_addr>
        <nodes>
          <node>wazuh-manager</node>
        </nodes>
        <hidden>no</hidden>
        <disabled>yes</disabled>
      </cluster>
      
      <!-- Rootcheck -->
      <rootcheck>
        <disabled>no</disabled>
        <check_files>yes</check_files>
        <check_trojans>yes</check_trojans>
        <check_dev>yes</check_dev>
        <check_sys>yes</check_sys>
        <check_pids>yes</check_pids>
        <check_ports>yes</check_ports>
        <check_if>yes</check_if>
        <frequency>43200</frequency>
        <rootkit_files>etc/shared/rootkit_files.txt</rootkit_files>
        <rootkit_trojans>etc/shared/rootkit_trojans.txt</rootkit_trojans>
        <skip_nfs>yes</skip_nfs>
      </rootcheck>
      
      <!-- Security Configuration Assessment -->
      <sca>
        <enabled>yes</enabled>
        <scan_on_start>yes</scan_on_start>
        <interval>12h</interval>
        <skip_nfs>yes</skip_nfs>
      </sca>
      
      <!-- Vulnerability detection -->
      <vulnerability-detection>
        <enabled>yes</enabled>
        <index-status>yes</index-status>
        <feed-update-interval>60m</feed-update-interval>
      </vulnerability-detection>
      
      <!-- Syscheck (File Integrity Monitoring) -->
      <syscheck>
        <disabled>no</disabled>
        <frequency>43200</frequency>
        <scan_on_start>yes</scan_on_start>
        <alert_new_files>yes</alert_new_files>
        
        <!-- Directories to monitor -->
        <directories>/etc,/usr/bin,/usr/sbin</directories>
        <directories>/bin,/sbin,/boot</directories>
        
        <!-- Ignore list -->
        <ignore>/etc/mtab</ignore>
        <ignore>/etc/hosts.deny</ignore>
        <ignore>/etc/mail/statistics</ignore>
        <ignore>/etc/random-seed</ignore>
        <ignore>/etc/random.seed</ignore>
        <ignore>/etc/adjtime</ignore>
        <ignore>/etc/httpd/logs</ignore>
        <ignore>/etc/utmpx</ignore>
        <ignore>/etc/wtmpx</ignore>
        <ignore>/etc/cups/certs</ignore>
        <ignore>/etc/dumpdates</ignore>
        <ignore>/etc/svc/volatile</ignore>
        
        <!-- Skip NFS mounts -->
        <skip_nfs>yes</skip_nfs>
        <skip_dev>yes</skip_dev>
        <skip_proc>yes</skip_proc>
        <skip_sys>yes</skip_sys>
        
        <!-- Real-time monitoring for critical files -->
        <directories realtime="yes">/etc/passwd,/etc/shadow,/etc/group</directories>
        <directories realtime="yes">/etc/sudoers,/etc/sudoers.d</directories>
      </syscheck>
      
      <!-- Log analysis -->
      <localfile>
        <log_format>syslog</log_format>
        <location>/var/ossec/logs/active-responses.log</location>
      </localfile>
      
      <!-- Analysis rules -->
      <ruleset>
        <decoder_dir>ruleset/decoders</decoder_dir>
        <rule_dir>ruleset/rules</rule_dir>
        <rule_exclude>0215-policy_rules.xml</rule_exclude>
        <list>etc/lists/audit-keys</list>
        <list>etc/lists/amazon/aws-eventnames</list>
        <list>etc/lists/security-eventchannel</list>
      </ruleset>
      
      <!-- Active response -->
      <global>
        <white_list>127.0.0.1</white_list>
        <white_list>10.10.0.0/24</white_list>
      </global>
      
      <command>
        <name>disable-account</name>
        <executable>disable-account</executable>
        <timeout_allowed>yes</timeout_allowed>
      </command>
      
      <command>
        <name>firewall-drop</name>
        <executable>firewall-drop</executable>
        <timeout_allowed>yes</timeout_allowed>
      </command>
      
      <!-- API configuration -->
      <api>
        <https>yes</https>
      </api>
      
      <!-- Indexer integration -->
      <indexer>
        <enabled>yes</enabled>
        <hosts>
          <host>https://wazuh-indexer:9200</host>
        </hosts>
        <ssl>
          <certificate_authorities>
            <ca>/var/ossec/etc/certs/root-ca.pem</ca>
          </certificate_authorities>
          <certificate>/var/ossec/etc/certs/manager.pem</certificate>
          <key>/var/ossec/etc/certs/manager-key.pem</key>
        </ssl>
      </indexer>
    </ossec_config>
---
# Wazuh Manager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-manager
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      # Force x86 node (lake) - Wazuh doesn't have ARM images
      nodeSelector:
        kubernetes.io/hostname: lake
      
      initContainers:
        # Wait for indexer to be ready
        - name: wait-for-indexer
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for Wazuh Indexer..."
              until nc -z wazuh-indexer 9200; do
                echo "Indexer not ready, waiting..."
                sleep 5
              done
              echo "Indexer is ready!"
        
        # Copy certs to manager location
        - name: setup-certs
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /var/ossec/etc/certs
              cp /certs/*.pem /var/ossec/etc/certs/ || true
              chown -R 1000:1000 /var/ossec/etc/certs || true
              chmod 600 /var/ossec/etc/certs/*-key.pem || true
          volumeMounts:
            - name: certs-volume
              mountPath: /certs
              readOnly: true
            - name: manager-data
              mountPath: /var/ossec/etc/certs
              subPath: certs
      
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.14.1
          
          env:
            - name: INDEXER_URL
              value: "https://wazuh-indexer:9200"
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-credentials
                  key: INDEXER_USERNAME
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-credentials
                  key: INDEXER_PASSWORD
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: "none"
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-credentials
                  key: WAZUH_API_USER
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-credentials
                  key: WAZUH_API_PASSWORD
            - name: WAZUH_AUTHD_PASS
              valueFrom:
                secretKeyRef:
                  name: wazuh-credentials
                  key: WAZUH_AUTHD_PASS
          
          ports:
            - containerPort: 1514
              name: agent-events
              protocol: TCP
            - containerPort: 1515
              name: enrollment
              protocol: TCP
            - containerPort: 55000
              name: api
              protocol: TCP
            - containerPort: 514
              name: syslog
              protocol: UDP
          
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          
          volumeMounts:
            - name: manager-data
              mountPath: /var/ossec/etc
              subPath: etc
            - name: manager-data
              mountPath: /var/ossec/logs
              subPath: logs
            - name: manager-data
              mountPath: /var/ossec/queue
              subPath: queue
            - name: manager-data
              mountPath: /var/ossec/var/multigroups
              subPath: multigroups
            - name: manager-data
              mountPath: /var/ossec/integrations
              subPath: integrations
            - name: manager-data
              mountPath: /var/ossec/active-response
              subPath: active-response
            - name: manager-data
              mountPath: /var/ossec/agentless
              subPath: agentless
            - name: manager-data
              mountPath: /var/ossec/wodles
              subPath: wodles
            - name: manager-data
              mountPath: /etc/filebeat
              subPath: filebeat
            - name: certs-volume
              mountPath: /var/ossec/etc/certs
              readOnly: true
            - name: manager-config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
          
          readinessProbe:
            tcpSocket:
              port: 55000
            initialDelaySeconds: 60
            periodSeconds: 30
          
          livenessProbe:
            tcpSocket:
              port: 1514
            initialDelaySeconds: 120
            periodSeconds: 60
      
      volumes:
        - name: manager-data
          persistentVolumeClaim:
            claimName: wazuh-manager-data
        - name: certs-volume
          persistentVolumeClaim:
            claimName: wazuh-certs
        - name: manager-config
          configMap:
            name: wazuh-manager-config