---
# Wazuh Agent DaemonSet
# Runs on every node to monitor the host system
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
  labels:
    app: wazuh-agent
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      # IMPORTANTE: Wazuh Agent no tiene imagen ARM oficial. 
      # Esto desplegará agentes SOLO en nodos AMD64 (lake).
      nodeSelector:
        kubernetes.io/arch: amd64

      # Run on all nodes including control-plane
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      
      hostNetwork: true
      hostPID: true
      hostIPC: true
      
      # Use node name as agent name
      initContainers:
        - name: configure-agent
          image: wazuh/wazuh-agent:4.14.1
          securityContext:
            privileged: true
          command:
            - /bin/bash
            - -c
            - |
              # Get node name from downward API
              NODE_NAME=$(cat /etc/nodename)
              echo "Configuring agent for node: $NODE_NAME"
              
              # Create agent config
              mkdir -p /var/ossec/etc
              
              cat > /var/ossec/etc/ossec.conf << 'AGENTCONFIG'
              <ossec_config>
                <client>
                  <server>
                    <address>wazuh-manager.wazuh.svc.cluster.local</address>
                    <port>1514</port>
                    <protocol>tcp</protocol>
                  </server>
                  <config-profile>ubuntu, ubuntu22, ubuntu22.04</config-profile>
                  <notify_time>10</notify_time>
                  <time-reconnect>60</time-reconnect>
                  <auto_restart>yes</auto_restart>
                  <crypto_method>aes</crypto_method>
                  <enrollment>
                    <enabled>yes</enabled>
                    <manager_address>wazuh-manager.wazuh.svc.cluster.local</manager_address>
                    <port>1515</port>
                    <agent_name>__NODE_NAME__</agent_name>
                    <authorization_pass_path>/var/ossec/etc/authd.pass</authorization_pass_path>
                  </enrollment>
                </client>

                <client_buffer>
                  <disabled>no</disabled>
                  <queue_size>5000</queue_size>
                  <events_per_second>500</events_per_second>
                </client_buffer>

                <!-- File integrity monitoring -->
                <syscheck>
                  <disabled>no</disabled>
                  <frequency>43200</frequency>
                  <scan_on_start>yes</scan_on_start>
                  <alert_new_files>yes</alert_new_files>
                  
                  <!-- Critical directories -->
                  <directories>/etc,/usr/bin,/usr/sbin</directories>
                  <directories>/bin,/sbin</directories>
                  <directories realtime="yes">/etc/passwd,/etc/shadow,/etc/group,/etc/sudoers</directories>
                  
                  <!-- K3s specific -->
                  <directories>/etc/rancher</directories>
                  <directories>/var/lib/rancher/k3s/server</directories>
                  
                  <!-- Ignore -->
                  <ignore>/etc/mtab</ignore>
                  <ignore>/etc/hosts.deny</ignore>
                  <ignore>/etc/adjtime</ignore>
                  <ignore>/etc/resolv.conf</ignore>
                  
                  <skip_nfs>yes</skip_nfs>
                  <skip_dev>yes</skip_dev>
                  <skip_proc>yes</skip_proc>
                  <skip_sys>yes</skip_sys>
                </syscheck>

                <!-- Rootcheck -->
                <rootcheck>
                  <disabled>no</disabled>
                  <check_files>yes</check_files>
                  <check_trojans>yes</check_trojans>
                  <check_dev>yes</check_dev>
                  <check_sys>yes</check_sys>
                  <check_pids>yes</check_pids>
                  <check_ports>yes</check_ports>
                  <check_if>yes</check_if>
                  <frequency>43200</frequency>
                  <skip_nfs>yes</skip_nfs>
                </rootcheck>

                <!-- SCA (Security Configuration Assessment) -->
                <sca>
                  <enabled>yes</enabled>
                  <scan_on_start>yes</scan_on_start>
                  <interval>12h</interval>
                  <skip_nfs>yes</skip_nfs>
                </sca>

                <!-- Log collection -->
                <localfile>
                  <log_format>syslog</log_format>
                  <location>/var/log/syslog</location>
                </localfile>

                <localfile>
                  <log_format>syslog</log_format>
                  <location>/var/log/auth.log</location>
                </localfile>

                <localfile>
                  <log_format>syslog</log_format>
                  <location>/var/log/kern.log</location>
                </localfile>

                <!-- Container logs -->
                <localfile>
                  <log_format>json</log_format>
                  <location>/var/log/containers/*.log</location>
                </localfile>

                <!-- K3s logs -->
                <localfile>
                  <log_format>syslog</log_format>
                  <location>/var/log/k3s.log</location>
                </localfile>

                <!-- Audit logs if available -->
                <localfile>
                  <log_format>audit</log_format>
                  <location>/var/log/audit/audit.log</location>
                </localfile>

                <!-- Active response -->
                <active-response>
                  <disabled>no</disabled>
                  <ca_store>/var/ossec/etc/wpk_root.pem</ca_store>
                  <ca_verification>yes</ca_verification>
                </active-response>

                <!-- Syscollector (inventory) -->
                <wodle name="syscollector">
                  <disabled>no</disabled>
                  <interval>1h</interval>
                  <scan_on_start>yes</scan_on_start>
                  <hardware>yes</hardware>
                  <os>yes</os>
                  <network>yes</network>
                  <packages>yes</packages>
                  <ports all="no">yes</ports>
                  <processes>yes</processes>
                </wodle>

                <!-- Docker listener -->
                <wodle name="docker-listener">
                  <disabled>no</disabled>
                </wodle>
              </ossec_config>
              AGENTCONFIG
              
              # Replace placeholder with actual node name
              sed -i "s/__NODE_NAME__/$NODE_NAME/g" /var/ossec/etc/ossec.conf
              
              # Copy authd password
              echo "$WAZUH_AUTHD_PASS" > /var/ossec/etc/authd.pass
              chmod 600 /var/ossec/etc/authd.pass
              
              echo "Agent configuration complete"
          env:
            - name: WAZUH_AUTHD_PASS
              valueFrom:
                secretKeyRef:
                  name: wazuh-credentials
                  key: WAZUH_AUTHD_PASS
          volumeMounts:
            - name: nodename
              mountPath: /etc/nodename
              subPath: nodename
            - name: ossec-etc
              mountPath: /var/ossec/etc
      
      containers:
        - name: wazuh-agent
          image: wazuh/wazuh-agent:4.14.1
          
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
                - NET_ADMIN
                - AUDIT_CONTROL
                - AUDIT_READ
          
          env:
            - name: WAZUH_MANAGER
              value: "wazuh-manager.wazuh.svc.cluster.local"
            - name: WAZUH_AGENT_GROUP
              value: "kubernetes"
            - name: WAZUH_AUTHD_PASS
              valueFrom:
                secretKeyRef:
                  name: wazuh-credentials
                  key: WAZUH_AUTHD_PASS
          
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          
          volumeMounts:
            # Agent persistent config
            - name: ossec-etc
              mountPath: /var/ossec/etc
            
            # Host filesystem (read-only for monitoring)
            - name: host-root
              mountPath: /host
              readOnly: true
            - name: host-var-log
              mountPath: /var/log
              readOnly: true
            - name: host-etc
              mountPath: /host/etc
              readOnly: true
            - name: host-usr
              mountPath: /host/usr
              readOnly: true
            
            # Docker/containerd socket for container monitoring
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: containerd-sock
              mountPath: /run/containerd/containerd.sock
              readOnly: true
            
            # K3s specific
            - name: k3s-rancher
              mountPath: /var/lib/rancher
              readOnly: true
            
            # Audit logs
            - name: host-audit
              mountPath: /var/log/audit
              readOnly: true
          
          livenessProbe:
            exec:
              command:
                - /var/ossec/bin/wazuh-control
                - status
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
      
      volumes:
        - name: nodename
          downwardAPI:
            items:
              - path: nodename
                fieldRef:
                  fieldPath: spec.nodeName
        
        - name: ossec-etc
          emptyDir: {}
        
        - name: host-root
          hostPath:
            path: /
            type: Directory
        
        - name: host-var-log
          hostPath:
            path: /var/log
            type: Directory
        
        - name: host-etc
          hostPath:
            path: /etc
            type: Directory
        
        - name: host-usr
          hostPath:
            path: /usr
            type: Directory
        
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
        
        - name: k3s-rancher
          hostPath:
            path: /var/lib/rancher
            type: DirectoryOrCreate
        
        - name: host-audit
          hostPath:
            path: /var/log/audit
            type: DirectoryOrCreate